Repository bookstore-README/front_bookstore-README, pull requests merged in 2024-01, with the labels that each got.

#7 [#6] tailwind 디자인 시스템 설정
  package-lock.json
  package.json
  public/favicon.ico
  public/fonts/.gitkeep
  public/icons/.gitkeep
  public/images/.gitkeep
  public/next.svg
  public/vercel.svg
  src/components/.gitkeep
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/layouts/.gitkeep
  src/libs/.gitkeep
  src/styles/globals.css
  src/types/.gitkeep
  src/utils/.gitkeep
  tailwind.config.ts
  tsconfig.json
Labels: style

#3 [#4] sign 공통 input 구현
  public/icons/check-icon.svg
  public/icons/eye-close.svg
  public/icons/eye-open.svg
  src/components/signInput/SignInput.tsx
Labels: feat

#11 [#12] issue template, classname prettier plugin 추가
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/auto_assign.yml
  .github/pull_request_template.md
  .prettierrc
  package-lock.json
  package.json
Labels: feat

#9 [#5] 약관동의 컴포넌트 제작
  public/icons/CameraImageIcon.svg
  public/icons/CheckIcon.svg
  public/icons/rightArrow.svg
  src/components/terms/terms.tsx
  src/styles/globals.css
Labels: feat

#19 fix : pr 템플릿 close number 수정
  .github/pull_request_template.md
Labels: fix

#17 [#18] 이미지 이름 카멜체로 수정
  public/icons/EyeClose.svg
  public/icons/EyeOpen.svg
  public/icons/check-icon.svg
Labels: fix

#27 [#14] 검색 헤더 구현
  public/icons/CartIcon.svg
  public/icons/CategoryIcon.svg
  public/icons/ProfileIcon.svg
  public/icons/SearchIcon.svg
  src/components/buttons/genreButton.tsx
  src/components/buttons/signUpButton.tsx
  src/components/header/NavigationTab.tsx
  src/components/header/cartButton.tsx
  src/components/header/categoryButton.tsx
  src/components/header/index.tsx
  src/components/header/myPageButton.tsx
  src/components/header/searchInput.tsx
  src/components/header/signInButton.tsx
  src/components/header/signOutButton.tsx
  src/layouts/HeaderLayout.tsx
  src/pages/api/mock.ts
  src/pages/bestsellers.tsx
  src/pages/community.tsx
  src/pages/custom.tsx
  src/pages/latest.tsx
  src/pages/mypage/genre.tsx
  src/pages/mypage/index.tsx
  src/styles/globals.css
Labels: feat

#30 [#20] community card UI 구현
  public/icons/Kebab.svg
  public/images/.gitkeep
  public/images/AngryEmoji.png
  public/images/CryEmoji.png
  public/images/ExitedEmoji.png
  public/images/HappyEmoji.png
  public/images/RedHeartEmoji.png
  public/images/SampleBookCover1.jpeg
  public/images/SampleBookCover2.jpeg
  public/images/SampleBookCover3.jpeg
  public/images/SampleBookCover4.jpeg
  src/components/buttons/kebabButton/kebabButton.tsx
  src/components/buttons/kebabButton/kebabDropDownButton.tsx
  src/components/communityCard/communityCard.tsx
  src/components/communityCard/emoji/emojiButton.tsx
  src/components/communityCard/emoji/emojiButtonContainer.tsx
  src/hooks/.gitkeep
  src/hooks/useShowDropDown.ts
  src/layouts/.gitkeep
  src/styles/globals.css
  src/utils/.gitkeep
  src/utils/cls.ts
  tailwind.config.ts
Labels: feat

#33 [#1] Feat/sign in/sign up page
  .vscode/settings.json
  public/icons/RightArrow.svg
  src/components/buttons/registerButton.tsx/RegisterButton.tsx
  src/components/errors/SignError.tsx
  src/components/signInput/SignInput.tsx
  src/components/socialCircle/SocialCircle.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/mypage/genre.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/types/signType.ts
  src/utils/checkSignInSignOut.ts
Labels: fix

#32 [#31] 날짜에 따른 주문 기능 구현
  .idea/.gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/front_bookstore-README.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/vcs.xml
  .vscode/settings.json
  package-lock.json
  package.json
  public/images/calendar.svg
  src/components/button/registerButton.tsx
  src/components/buttons/registerButton.tsx/RegisterButton.tsx
  src/components/dropDown/DropDown.tsx
  src/components/dropDown/DropDownItem.tsx
  src/components/editPassword/editPassword.tsx
  src/components/editProfile/editProfile.tsx
  src/components/orderDate/OrderDate.tsx
  src/components/socialCircle/SocialCircle.tsx
  src/components/terms/dist/terms.js
  src/components/terms/terms.tsx
  src/hooks/useShowDropDown.ts
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/pages/test/index.tsx
  src/styles/globals.css
  src/utils/getTimeAgo.ts
  tailwind.config.ts
Labels: feat, style

#28 [#10] 마이페이지 리뷰컴포넌트, 주문컴포넌트 생성
  public/icons/DeleteIcon.svg
  public/icons/EditIcon.svg
  public/icons/FilledStar.svg
  public/icons/UnfilledStar.svg
  src/components/bookComponents/bookAuthor/bookAuthor.tsx
  src/components/bookComponents/bookRating/bookRating.tsx
  src/components/bookOrderCard/bookOrderCard.tsx
  src/components/bookReviewCard/bookReviewCard.tsx
  src/types/bookOrderType.ts
  src/types/bookReviewType.ts
Labels: feat

#46 [#45] 폴더수정 및 파일명 수정
  src/components/book/bookAuthor/bookAuthor.tsx
  src/components/book/bookRating/bookRating.tsx
  src/components/button/cartButton.tsx
  src/components/button/categoryButton.tsx
  src/components/button/genreButton.tsx
  src/components/button/kebab/kebabButton.tsx
  src/components/button/kebab/kebabDropDownButton.tsx
  src/components/button/myPageButton.tsx
  src/components/button/register/registerButton.tsx
  src/components/button/signInButton.tsx
  src/components/button/signOutButton.tsx
  src/components/button/signUpButton.tsx
  src/components/card/bookOrderCard/bookOrderCard.tsx
  src/components/card/bookReviewCard/bookReviewCard.tsx
  src/components/card/communityCard/communityCard.tsx
  src/components/card/communityCard/emoji/emojiButton.tsx
  src/components/card/communityCard/emoji/emojiButtonContainer.tsx
  src/components/chip/socialCircle.tsx
  src/components/communityCard/emoji/emojiButtonContainer.tsx
  src/components/container/orderDate/orderCount.tsx
  src/components/container/orderDate/orderDate.tsx
  src/components/container/orderDate/orderOverView.tsx
  src/components/container/terms/terms.tsx
  src/components/dropDown/dropDown.tsx
  src/components/dropDown/dropDownItem.tsx
  src/components/header/index.tsx
  src/components/header/navigation.tsx
  src/components/input/searchInput.tsx
  src/components/input/signInput/signInput.tsx
  src/components/layout/headerLayout.tsx
  src/components/profile/editPassword/editPassword.tsx
  src/components/profile/editProfile/editProfile.tsx
  src/pages/mypage/genre.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  tsconfig.json
Labels: refactor

#58 [#57] signinput 디자인 수정
  src/components/input/signInput/signInput.tsx
Labels: style

#51 [#42] 책 미리보기 컴포넌트 제작
  .prettierrc
  public/icons/BookLabelIcon.svg
  src/components/book/bookAuthor/bookAuthor.tsx
  src/components/book/previewBookInfo/previewBookInfo.tsx
  src/components/container/terms/terms.tsx
  src/constants/.gitkeep
  src/constants/sign.ts
  src/pages/_document.tsx
  src/pages/test/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: feat

#61 [#57] sign input 디자인 일부 수정
  src/components/input/signInput/signInput.tsx
  src/styles/globals.css
Labels: style

#60 [#59] signIn && signout css수정
  src/components/errors/signError.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/styles/globals.css
Labels: style

#66 [#62] 책 미리보기 컴포넌트 라벨색변경 기능+가격표시 추가
  src/components/book/previewBookInfo/previewBookInfo.tsx
  src/constants/price.ts
  src/pages/test/index.tsx
Labels: refactor

#49 [#41] 케밥버튼 수정
  src/components/button/kebab/kebabDropDownButton.tsx
  src/components/card/communityCard/communityCard.tsx
  src/pages/test/index.tsx
Labels: refactor, style

#50 [#34] main page layout & scrolltoup 버튼
  public/icons/ScrollToTopButton.svg
  src/components/button/scrollToTopButton.tsx
  src/components/layout/headerLayout.tsx
  src/components/layout/mainLayout.tsx
  src/hooks/useInfinite.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/store/state.ts
  tailwind.config.ts
Labels: feat

#72 [#71] scroll to up ref 수정
  src/components/button/scrollToTopButton.tsx
  src/components/layout/headerLayout.tsx
  src/components/layout/mainLayout.tsx
  src/store/state.ts
Labels: refactor, Priority : Critical

#70 [#74] header 구현
  custom.d.ts
  public/icons/CartIcon.svg
  public/icons/CategoryIcon.svg
  public/icons/GreenRightArrow.svg
  public/icons/HeartIcon.svg
  public/icons/ProfileIcon.svg
  src/components/button/cartButton.tsx
  src/components/button/categoryButton.tsx
  src/components/button/header/bookmarkButton.tsx
  src/components/button/header/cartButton.tsx
  src/components/button/header/categoryButton.tsx
  src/components/button/header/categoryTabButton.tsx
  src/components/button/header/myPageButton.tsx
  src/components/button/header/readmeButton.tsx
  src/components/button/header/selectedAllButton.tsx
  src/components/button/header/writePostButton.tsx
  src/components/button/kebab/kebabDropDownButton.tsx
  src/components/button/myPageButton.tsx
  src/components/header/categoryTab.tsx
  src/components/header/index.tsx
  src/components/header/navigation.tsx
  src/components/header/navigationTab.tsx
  src/components/input/searchInput.tsx
  src/components/layout/headerLayout.tsx
  src/components/layout/mainLayout.tsx
  src/pages/api/mock.ts
  src/pages/bestseller/index.tsx
  src/pages/bestsellers.tsx
  src/pages/bookmarked/index.tsx
  src/pages/cart/index.tsx
  src/pages/community.tsx
  src/pages/community/index.tsx
  src/pages/custom.tsx
  src/pages/custom/index.tsx
  src/pages/domestic/[category]/index.tsx
  src/pages/domestic/index.tsx
  src/pages/foreign/[category]/page.tsx
  src/pages/foreign/index.tsx
  src/pages/latest.tsx
  src/pages/newest/index.tsx
  src/pages/test/index.tsx
  src/styles/globals.css
  src/utils/getNumItemsOfCart.ts
Labels: feat

#76 [#75] 선호장르 섹션 구현
  src/components/button/editToggleButton.tsx
  src/components/button/genreButton.tsx
  src/pages/api/mock.ts
  src/pages/mypage/genre.tsx
Labels: feat

#56 [#43] main페이지에 들어갈 신간도서 carousel구현
  .eslintrc.json
  package-lock.json
  package.json
  public/icons/CarouselLeftActivateArrow.svg
  public/icons/CarouselLeftInActivateArrow.svg
  public/icons/CarouselRightActivateArrow.svg
  public/icons/CarouselRightInActivateArrow.svg
  src/components/carousel/carousel.tsx
  src/components/carousel/carouselCard.tsx
  src/hooks/useCarouselEnv.ts
  src/hooks/useClientEffect.ts
  src/hooks/useResizeEffect.ts
  src/pages/test/carouselTest.tsx
  src/types/carouselType.ts
  src/utils/checkResponsiveEnv.ts
  src/utils/inrange.ts
  src/utils/registerDragEvent.ts
Labels: feat

#55 [#35] 메인 페이지에 들어갈 오늘의 도서 컴포넌트 생성
  src/components/book/bookRating/bookRating.tsx
  src/components/card/todayBestBookCard/TodayBestBookCard.tsx
  src/components/skeleton/skeletonTodayBestBook.tsx
  src/components/todayBestCorner/todayBestCorner.tsx
  src/components/todayBestCorner/todayBestSlider.tsx
  src/hooks/useWindowInnerWidth.ts
  src/hooks/useWithSlider.tsx
  src/pages/api/todayBestMock.ts
  src/pages/test/index.tsx
  src/types/cardType.ts
Labels: feat
