Repository bookstore-README/front_bookstore-README, pull requests merged in 2024-02, with the labels that each got.

#87 [#86] 폴더 구조 변경
  src/components/book/bookOverViewCard.tsx
  src/components/button/genreButton.tsx
  src/components/header/categoryTab.tsx
  src/components/header/index.tsx
  src/components/header/navigationTab.tsx
  src/components/modal/AlertModal.tsx
  src/components/todayBestCorner/todayBestCorner.tsx
  src/layouts/headerLayout.tsx
  src/layouts/mainLayout.tsx
  src/layouts/modalLayout.tsx
  src/pages/api/mock/hello.ts
  src/pages/api/mock/mock.ts
  src/pages/api/mock/todayBestMock.ts
  src/pages/index.tsx
  src/pages/mypage/genre.tsx
  tsconfig.json
Labels: Priority : Critical

#96 [#95] mainlayout 수정
  src/components/layout/mainLayout.tsx
  src/pages/index.tsx
Labels: bug, Priority : High

#98 [#93] 외부이미지 로드 설정
  next.config.mjs
Labels: fix, Priority : High

#82 [#79] 찜페이지 구현
  public/icons/CheckBox.svg
  public/icons/CheckedCheckBox.svg
  public/icons/Close.svg
  src/hooks/useInfinite.ts
  src/pages/api/wishMock.ts
  src/pages/wish/index.tsx
Labels: feat, style

#97 [#64][#65] 베스트셀러/신간 페이지 제작
  package-lock.json
  package.json
  src/components/book/bookRating/bookRating.tsx
  src/components/book/previewBookInfo/previewBookInfo.tsx
  src/components/button/actionButton.tsx
  src/components/card/bookOverviewCard/bookOverViewCard.tsx
  src/components/card/bookOverviewCard/bookOverViewCardList.tsx
  src/components/layout/bestSellerLayout.tsx
  src/components/layout/sidebarLayout.tsx
  src/components/toast/toast.tsx
  src/pages/_app.tsx
  src/pages/api/mock/bestSellerMock.ts
  src/pages/bestseller/index.tsx
  src/pages/newest/index.tsx
  src/pages/test/index.tsx
Labels: feat

#100 [#89] 상품상세페이지에 들어갈 북 카드 컴포넌트 / 책 가격 표시 컴포넌트 / 책 카테고리 표시 컴포넌트 구현
  public/icons/ShareIcon.svg
  src/components/book/bookCategory/bookCategory.tsx
  src/components/book/bookPrice/bookPrice.tsx
  src/components/button/likeButton.tsx
  src/components/card/bookDetailCard/bookDetailCard.tsx
  src/pages/api/mock/bookDetailMock.ts
  src/pages/bookdetail/[bookId].tsx
  src/pages/bookdetail/index.tsx
  src/types/cardType.ts
Labels: feat

#84 [#68, #69] 커뮤니티 페이지 UI, 기능구현
  public/icons/Close.svg
  public/icons/ScrollToTopButton.svg
  src/components/button/actionButton.tsx
  src/components/button/header/writePostButton.tsx
  src/components/button/kebab/kebabButton.tsx
  src/components/button/kebab/kebabDropDownButton.tsx
  src/components/button/register/registerButton.tsx
  src/components/button/scrollToTopButton.tsx
  src/components/card/communityCard/communityCard.tsx
  src/components/carousel/carouselCard.tsx
  src/components/header/navigationTab.tsx
  src/components/header/pageTab.tsx
  src/components/layout/communityLayout.tsx
  src/components/layout/mainLayout.tsx
  src/components/modal/addCommunityCard/addCommunityCard.tsx
  src/components/modal/addCommunityCard/addCommunityCardForm.tsx
  src/components/modal/addCommunityCard/carousel.tsx
  src/components/modal/alertModal.tsx
  src/components/modal/modalLayout.tsx
  src/pages/_document.tsx
  src/pages/api/mock.ts
  src/pages/community/index.tsx
  src/pages/community/writeme.tsx
  src/styles/globals.css
  src/types/communityCardType.ts
  src/utils/checkResponsiveEnv.ts
  src/utils/cls.ts
  src/utils/registerDragEvent.ts
  tsconfig.json
Labels: feat, Priority : medium

#107 [#89] 상품상세페이지 하단 레이아웃, 좌측 구매하기버튼 sticky 레이아웃 구현
  src/components/book/bookInformation/bookInformation.tsx
  src/components/book/bookPrice/bookPrice.tsx
  src/components/book/percentage/percentage.tsx
  src/components/book/percentage/reviewPercentageOverview.tsx
  src/components/button/bookDetailNav.tsx
  src/components/card/bookDetailCard/bookDetailCard.tsx
  src/components/card/bookReviewCard/bookReviewCard.tsx
  src/components/card/bookReviewCard/myReviewCard.tsx
  src/components/card/bookReviewCard/reviewOverviewCard.tsx
  src/components/container/refundTerm/refundTerm.tsx
  src/components/review/review.tsx
  src/pages/api/mock/bookDetailMock.ts
  src/pages/bookdetail/[bookId].tsx
  src/types/bookDetailtype.ts
  src/types/bookReviewType.ts
Labels: feat, style, Priority : medium

#113 [#112] 메인페이지 베스트셀러 섹션 구현
  src/components/button/genre/customGenreButton.tsx
  src/components/button/genre/genreButton.tsx
  src/components/button/moreLinkButton.tsx
  src/components/container/bestsellerSection/bestsellerSection.tsx
  src/components/container/customSection/customSection.tsx
  src/components/container/customSection/nonLoggedInCustomSection.tsx
  src/components/container/customSection/nonSelectedCustomSection.tsx
  src/components/container/customSection/recommendationContent.tsx
  src/pages/api/mock/bestSellerMock.ts
  src/pages/api/mock/customSectionMock.ts
  src/pages/index.tsx
  src/pages/mypage/genre.tsx
Labels: feat

#117 [#74] 헤더 아이콘 및 경로 수정
  public/icons/HeartIcon.svg
  src/components/button/header/bookmarkButton.tsx
  src/components/button/header/myPageButton.tsx
Labels: style

#130 [#119] pages 폴더 구조 수정
  src/components/carousel/carousel.tsx
  src/components/container/bestsellerSection/bestsellerSection.tsx
  src/components/header/navigationTab.tsx
  src/pages/domestic/[category]/bestseller/index.tsx
  src/pages/domestic/[category]/newest/index.tsx
  src/pages/domestic/bestseller/index.tsx
  src/pages/domestic/newest/index.tsx
  src/pages/foreign/[category]/bestseller/index.tsx
  src/pages/foreign/[category]/newest/index.tsx
  src/pages/foreign/bestseller/index.tsx
  src/pages/foreign/newest/index.tsx
Labels: fix, Priority : Critical

#138 [#131] 사이드바에서 링크가 잘 적용되게끔 수정
  src/components/button/sidebar/sidebarRegionButton.tsx
  src/components/button/sidebar/sidebarTab.tsx
  src/components/button/sidebar/sidebarTabController.tsx
  src/components/header/navigationTab.tsx
  src/components/layout/sidebarLayout.tsx
  src/components/sidebar/sidebar.tsx
  src/pages/domestic/[category]/bestseller/index.tsx
  src/pages/domestic/[category]/newest/index.tsx
  src/pages/domestic/bestseller/index.tsx
  src/pages/domestic/newest/index.tsx
  src/pages/foreign/[category]/bestseller/index.tsx
  src/pages/foreign/[category]/newest/index.tsx
  src/pages/foreign/bestseller/index.tsx
  src/pages/foreign/newest/index.tsx
  src/types/sidebarType.ts
Labels: fix, refactor, Priority : High

#128 [#127] Carousel 버그 FIX
  src/components/carousel/carousel.tsx
  src/components/carousel/carouselCard.tsx
  src/components/carousel/categoryCarousel.tsx
Labels: fix

#139 [#118] PreviewbookInfo 외부 이미지 사용가능하게 적용
  src/components/book/previewBookInfo/previewBookInfo.tsx
  src/components/card/bookOverviewCard/bookOverViewCard.tsx
  src/components/layout/bestSellerLayout.tsx
  src/components/skeleton/previewBookInfo/skeleton.tsx
  src/components/skeleton/previewBookInfo/skeletonBox.tsx
  src/constants/previewBookSize.ts
  src/pages/api/mock/bestSellerMock.ts
  src/pages/test/index.tsx
  src/types/previewBookInfoType.ts
Labels: refactor

#142 fix : deploy 변수 수정
  .github/workflows/deploy.yml
Labels: fix, Priority : Critical

#135 [#134] 헤더 링크 연결 변경
  src/components/button/header/customBookButton.tsx
  src/components/header/navigationTab.tsx
Labels: fix

#132 [#122] 제품상세페이지의 리뷰 컴포넌트 구현
  src/components/card/bookReviewCard/bookReviewCard.tsx
  src/components/card/bookReviewCard/myReviewCard.tsx
  src/components/card/bookReviewCard/reviewOverviewCard.tsx
  src/components/review/review.tsx
  src/pages/api/mock/bookDetailMock.ts
  src/types/bookReviewType.ts
Labels: feat, style

#149 [#143] 제품상세페이지에 들어갈 order 컴포넌트 구현
  src/components/book/bookCategory/bookCategory.tsx
  src/components/card/bookDetailCard/bookDetailCard.tsx
  src/components/card/bookDetailCard/bookDetailImg.tsx
  src/components/card/bookDetailCard/bookDetailInfo.tsx
  src/components/layout/sidebarLayout.tsx
  src/components/orderNavigator/footerOrderNavitgator.tsx
  src/components/orderNavigator/sideOrderNavigator.tsx
  src/components/orderNavigator/staticOrderNavigator.tsx
  src/pages/bookdetail/[bookId].tsx
Labels: feat, style

#148 [#147] 책 미리보기 라벨 추가
  public/icons/BookLabelBottomGrayIcon.svg
  public/icons/BookLabelBottomIcon.svg
  src/components/book/previewBookInfo/authors.tsx
  src/components/book/previewBookInfo/category.tsx
  src/components/book/previewBookInfo/previewBookInfo.tsx
  src/components/book/previewBookInfo/price.tsx
  src/components/book/previewBookInfo/title.tsx
  src/components/card/bookOverviewCard/bookOverViewCard.tsx
  src/components/skeleton/bookOverviewCard/skeleton.tsx
  src/components/skeleton/previewBookImage/skeleton.tsx
  src/constants/size/previewBookImageSize.ts
  src/pages/api/mock/bestSellerMock.ts
  src/pages/test/index.tsx
  tailwind.config.ts
Labels: feat, refactor

#155 [#15] 마이페이지 헤더 구현
  src/components/button/header/TabButton.tsx
  src/components/container/genreSection/genreSection.tsx
  src/components/header/mypageTab.tsx
  src/components/header/settingTab.tsx
  src/components/layout/headerLayout.tsx
  src/pages/mypage/community/index.tsx
  src/pages/mypage/order/index.tsx
  src/pages/mypage/review/index.tsx
  src/pages/mypage/setting/editPassword/index.tsx
  src/pages/mypage/setting/editProfile/index.tsx
  src/pages/mypage/setting/selectGenre/index.tsx
Labels: feat

#154 [#153] 선호장르 선택 섹션 구현
  src/components/container/genreSection/genreSection.tsx
Labels: feat

#158 [#157] dropDown 공용 컴퍼넌트화
  src/components/dropDown/dropDown.tsx
  src/components/dropDown/dropDownItem.tsx
  src/constants/dropDownSize.ts
  src/pages/test/carouselTest.tsx
  src/pages/test/dropDownTest.tsx
Labels: refactor

#159 [#160] [#167] 인풋 컴포넌트 일부 디자인 수정 / BookOrderCard 컴포넌트 일부 디자인 수정
  src/components/card/bookOrderCard/bookOrderCard.tsx
  src/components/input/signInput/signInput.tsx
Labels: fix, style, Priority : Low

#146 [#140] 회원가입페이지 유효성 검사 에러 해결
  src/components/container/terms/terms.tsx
  src/components/errors/signError.tsx
  src/pages/signup/index.tsx
  src/types/signType.ts
  src/utils/checkSignInSignOut.ts
Labels: fix

#168 [#167] bookOrderCardList 컴포넌트 제작
  src/components/card/bookOrderCard/bookOrderCard.tsx
  src/components/card/bookOrderCard/bookOrderCardList.tsx
  src/components/container/orderDate/orderCount.tsx
  src/components/layout/myOrderLayOut.tsx
  src/pages/api/mock/bookOrderMock.ts
  src/pages/mypage/order/index.tsx
  src/pages/test/index.tsx
  src/pages/test/orderPage/index.tsx
  src/types/bookOrderType.ts
Labels: feat

#169 [#166] api curd fu 추가
  src/api/book.ts
  src/api/bookmark.ts
  src/api/cart.ts
  src/api/category.ts
  src/api/community.ts
  src/api/delivery.ts
  src/api/member.ts
  src/api/order.ts
  src/api/payment.ts
  src/api/review.ts
  src/libs/.gitkeep
  src/libs/instance.ts
  src/types/api/book.ts
  src/types/api/community.ts
  src/types/api/member.ts
Labels: feat

#156 [#123] modal UI
  next.config.mjs
  package-lock.json
  package.json
  public/icons/EraserSearchValue.svg
  public/icons/Line.svg
  public/icons/NextIcon.svg
  public/icons/PrevIcon.svg
  public/icons/UnfilledStar.svg
  src/api/address.ts
  src/components/book/bookRating/bookRating.tsx
  src/components/button/header/categoryTabButton.tsx
  src/components/button/pagination.tsx
  src/components/button/register/registerButton.tsx
  src/components/header/navigationTab.tsx
  src/components/input/modalSearchInput.tsx
  src/components/input/radio.tsx
  src/components/input/textarea.tsx
  src/components/modal/addCommunityCard/addCommunityCard.tsx
  src/components/modal/addCommunityCard/addCommunityCardForm.tsx
  src/components/modal/addCommunityCard/carousel.tsx
  src/components/modal/addCommunityCard/index.tsx
  src/components/modal/addCommunityCard/previewBookInfoPagination.tsx
  src/components/modal/addReview/addReviewForm.tsx
  src/components/modal/addReview/index.tsx
  src/components/modal/addReview/titleContentTable.tsx
  src/components/modal/alertModal/index.tsx
  src/components/modal/findAddress/AddressItem.tsx
  src/components/modal/findAddress/doFindAddress.tsx
  src/components/modal/findAddress/findAddressForm.tsx
  src/components/modal/findAddress/findAddressWrapper.tsx
  src/components/modal/findAddress/index.tsx
  src/components/modal/findAddress/notFindAddress.tsx
  src/components/modal/getRefund/getRefundForm.tsx
  src/components/modal/getRefund/index.tsx
  src/components/modal/modalContainer.tsx
  src/components/modal/modalLayout.tsx
  src/constants/queryKey.ts
  src/hooks/useFormControl.ts
  src/hooks/usePagination.ts
  src/hooks/useSearchDebounce.ts
  src/pages/test/index.tsx
  src/store/state.ts
  src/types/address.ts
  src/types/onClickType.ts
  tsconfig.json
Labels: feat

#180 헤더 수정
  src/components/button/header/cartButton.tsx
  src/components/button/header/myPageButton.tsx
  src/components/header/index.tsx
  src/components/header/mypageTab.tsx
  src/components/layout/mainLayout.tsx
  src/pages/mypage/order/index.tsx
Labels: fix

#170 [#165] 메인페이지 오늘의 추천도서 컴포넌트 수정
  src/components/book/bookAuthor/bookAuthor.tsx
  src/components/book/bookCategory/bookCategory.tsx
  src/components/card/todayBestBookCard/TodayBestBookCard.tsx
  src/components/container/todayBestSection/todayBestSection.tsx
  src/components/container/todayBestSection/todayBestSlider.tsx
  src/components/skeleton/todayBestBookSkeleton/skeletonTodayBestBook.tsx
  src/pages/api/mock/todayBestSectionMock.ts
  src/pages/api/todayBestMock.ts
  src/pages/index.tsx
  src/types/cardType.ts
Labels: refactor, style

#172 [#171] dropDown 컴퍼넌트 background색상추가
  src/components/dropDown/dropDown.tsx
Labels: style

#150 [#101] 도서/신간 페이지 공용 컴포넌트 스켈레톤 UI 제작
  src/components/book/previewBookInfo/authors.tsx
  src/components/book/previewBookInfo/category.tsx
  src/components/book/previewBookInfo/previewBookInfo.tsx
  src/components/book/previewBookInfo/price.tsx
  src/components/book/previewBookInfo/title.tsx
  src/components/card/bookOverviewCard/bookOverViewCard.tsx
  src/components/skeleton/bookOverviewCard/skeleton.tsx
  src/components/skeleton/previewBookImage/skeleton.tsx
  src/constants/style/previewBookImageSize.ts
  src/constants/style/skeletonCommonStyle.ts
  src/pages/test/index.tsx
Labels: feat

#174 주문조회 페이지 조립 (배송상태 컴포넌트 포함)
  src/components/book/bookAuthor/bookAuthor.tsx
  src/components/book/bookCategory/bookCategory.tsx
  src/components/book/bookTitle/bookTitle.tsx
  src/components/card/bookOrderCard/bookOrderCard.tsx
  src/components/card/bookOrderCard/bookOrderCardList.tsx
  src/components/container/orderDate/orderCount.tsx
  src/components/container/orderDate/orderDate.tsx
  src/components/container/orderDate/orderOverView.tsx
  src/components/layout/mainLayout.tsx
  src/components/layout/myOrderLayOut.tsx
  src/pages/api/mock/bookOrderMock.ts
  src/pages/mypage/order/index.tsx
  src/pages/mypage/setting/editProfile/index.tsx
Labels: help wanted, feat

#181 [#144] 카테고리 페이지 조립
  src/components/container/eventSection/eventSection.tsx
  src/components/layout/sidebarLayout.tsx
  src/components/list/bookReviewList/bookReviewList.tsx
  src/components/list/categoryBookList/categoryBookList.tsx
  src/pages/api/mock/domesticBookListMock.ts
  src/pages/domestic/[category]/index.tsx
  src/pages/domestic/index.tsx
  src/pages/foreign/[category]/index.tsx
  src/pages/foreign/index.tsx
Labels: style, Priority : High

#187 [#176] 설정 페이지-프로필수정 조립
  src/components/layout/settingPageLayout.tsx
  src/components/profile/editProfile/editProfile.tsx
  src/pages/mypage/setting/editProfile/index.tsx
  src/types/editProfileTypes.ts
Labels: feat

#188 [#177] 설정 페이지-선호장르 선택 조립
  src/components/container/genreSection/genreSection.tsx
  src/components/layout/settingPageLayout.tsx
  src/pages/mypage/setting/selectGenre/index.tsx
Labels: feat

#190 [#178]설정 페이지-비밀번호 변경 조립
  src/components/input/signInput/signInput.tsx
  src/components/layout/settingPageLayout.tsx
  src/components/profile/editPassword/editPassword.tsx
  src/pages/mypage/setting/editPassword/index.tsx
Labels: feat

#197 [#196] 푸터 생성
  public/icons/FigmaIcon.svg
  public/icons/GatherIcon.svg
  public/icons/GithubIcon.svg
  src/components/footer/footer.tsx
  src/pages/test/footer/index.tsx
Labels: style, Priority : Low

#192 [#191] 마이 페이지- 나의 커뮤니티 글 조립
  src/components/card/communityCard/communityCardList.tsx
  src/components/layout/communityLayout.tsx
  src/components/layout/settingPageLayout.tsx
  src/pages/domestic/bestseller/index.tsx
  src/pages/mypage/community/index.tsx
Labels: feat

#193 [#175] 마이페이지- 나의리뷰 조립
  src/components/card/bookReviewCard/myReviewCard.tsx
  src/components/card/bookReviewCard/myReviewCardList.tsx
  src/components/layout/settingPageLayout.tsx
  src/pages/api/mock/myReviewMock.ts
  src/pages/mypage/review/index.tsx
Labels: feat

#152 [#151] 장바구니 페이지 모달 연결 및 아이콘 변경
  public/icons/CheckBox.svg
  public/icons/CheckedCheckBox.svg
  src/components/cart/cartPayment.tsx
  src/components/layout/vacantLayout.tsx
  src/components/modal/cart/cartModal.tsx
  src/components/modal/cart/cartPaymentModal.tsx
  src/pages/cart/index.tsx
Labels: feat, style

#216 [#161] 카테고리 사이드바 api 연결 및 전역 상태관리
  src/api/category.ts
  src/components/button/sidebar/sidebarRegionButton.tsx
  src/components/button/sidebar/sidebarTab.tsx
  src/components/button/sidebar/sidebarTabController.tsx
  src/components/container/initialContainer/initialContainer.tsx
  src/components/layout/sidebarLayout.tsx
  src/components/list/categoryBookList/categoryBookList.tsx
  src/components/sidebar/sidebar.tsx
  src/hooks/useGetCategory.tsx
  src/hooks/useSetLocatedCategory.ts
  src/libs/instance.ts
  src/pages/_app.tsx
  src/pages/domestic/[category]/bestseller/index.tsx
  src/pages/domestic/[category]/index.tsx
  src/pages/domestic/[category]/newest/index.tsx
  src/pages/domestic/bestseller/index.tsx
  src/pages/domestic/index.tsx
  src/pages/domestic/newest/index.tsx
  src/pages/foreign/[category]/bestseller/index.tsx
  src/pages/foreign/[category]/index.tsx
  src/pages/foreign/[category]/newest/index.tsx
  src/pages/foreign/bestseller/index.tsx
  src/pages/foreign/index.tsx
  src/pages/foreign/newest/index.tsx
  src/store/state.ts
  src/types/api/category.ts
  src/types/sidebarType.ts
Labels: feat, Priority : High

#213 [#212] 마이페이지 스타일 리팩토링
  src/components/card/bookOrderCard/bookOrderCard.tsx
  src/components/card/bookOrderCard/bookOrderCardList.tsx
  src/components/card/bookOrderCard/bookOrderEmptyCard.tsx
  src/components/card/bookReviewCard/myReviewCard.tsx
  src/components/container/genreSection/genreSection.tsx
  src/components/layout/bestSellerLayout.tsx
  src/components/layout/myOrderLayOut.tsx
  src/components/layout/settingPageLayout.tsx
  src/components/profile/editProfile/editProfile.tsx
  src/pages/mypage/order/index.tsx
Labels: refactor

#199 [#198] orderDate컴퍼넌트 수정
  src/components/container/orderDate/orderDate.tsx
  src/pages/api/mock/bookOrderMock.ts
  src/pages/test/dropDownTest.tsx
Labels: fix

#202 [#163] Refund-modal 수정
  src/components/input/input.tsx
  src/components/input/radio.tsx
  src/components/input/textarea.tsx
  src/components/modal/addCommunityCard/addCommunityCardForm.tsx
  src/components/modal/addReview/addReviewForm.tsx
  src/components/modal/getRefund/getRefundForm.tsx
  src/components/modal/getRefund/refundPrice.tsx
  src/constants/dropDownMenu 2.ts
  src/constants/dropDownMenu.ts
  src/hooks/useFormControl.ts
  src/pages/test/modaltest 2.tsx
  src/pages/test/modaltest.tsx
  tsconfig.json
Labels: fix

#205 [#203] alertmodal수정
  src/components/button/register/registerButton.tsx
  src/components/modal/addReview/titleContentTable.tsx
  src/components/modal/alertModal/index.tsx
  src/components/modal/cart/cartModal.tsx
Labels: feat, style, Priority : Low

#214 [#209] 결제페이지 3번 UI
  src/components/card/totalPaymentCard/index.tsx
  src/components/card/totalPaymentCard/totalPrice.tsx
  src/components/container/terms/terms.tsx
  src/constants/sign.ts
  src/pages/signup/index.tsx
  src/pages/test/payment/index.tsx
Labels: fix, feat, style, Priority : medium

#215 [#211] 결제페이지 5번 UI
  src/components/card/infoCard.tsx
  src/components/card/titleContentCard/index.tsx
  src/components/card/titleContentCard/titleContent.tsx
  src/components/container/orderCompletedSection/index.tsx
  src/constants/payment.ts
  src/pages/test/payment/index.tsx
Labels: feat, style, Priority : Low

#201 [#200] dropDown 글자깨짐&&button type변경
  src/components/dropDown/dropDown.tsx
  src/pages/test/dropDownTest.tsx
Labels: fix

#224 [#116] 국내전체, 외국전체 카테고리 페이지 무한스크롤 api 연결
  src/components/container/bookReviewList/bookReviewList.tsx
  src/components/container/categoryBookList/mainCategoryBookList.tsx
  src/components/container/categoryBookList/subCategoryBookList.tsx
  src/components/list/.gitkeep
  src/constants/orderList.ts
  src/hooks/useCustomInfiniteQuery.ts
  src/hooks/useGetCategory.tsx
  src/hooks/useGetCategoryId.ts
  src/pages/domestic/[category]/index.tsx
  src/pages/domestic/index.tsx
  src/pages/foreign/[category]/index.tsx
  src/pages/foreign/index.tsx
Labels: feat

#223 [#222] 찜페이지 폴더명변경(wish => bookmarked)
  src/pages/bookmarked/index.tsx
  src/pages/wish/index.tsx
Labels: fix

#225 [#207] api함수에 useQuery 감싸기
  src/api/basket.ts
  src/api/book.ts
  src/api/bookmark.ts
  src/api/cart.ts
  src/api/category.ts
  src/api/community.ts
  src/api/delivery.ts
  src/api/member.ts
  src/api/order.ts
  src/api/payment.ts
  src/api/review.ts
  src/components/card/totalPaymentCard/totalPrice.tsx
  src/components/modal/alertModal/index.tsx
  src/constants/queryKey.ts
  src/hooks/useFormControl.ts
  src/pages/community/index.tsx
  src/pages/test/modaltest 2.tsx
  src/types/api/basket.ts
  src/types/api/book.ts
  src/types/api/bookmark.ts
  src/types/api/community.ts
  src/types/api/member.ts
  src/utils/reactQuery.ts
Labels: refactor, Priority : High

#219 [#141] 회원가입 페이지 API연결
  src/hooks/useSignUpMutation.ts
  src/pages/signup/index.tsx
  src/utils/checkSignInSignOut.ts
Labels: feat

#246 [#236] 하위 카테고리페이지 무한스크롤 api 연결
  src/components/button/sidebar/sidebarTab.tsx
  src/components/button/sidebar/sidebarTabController.tsx
  src/components/container/categoryBookList/mainCategoryBookList.tsx
  src/components/container/categoryBookList/subCategoryBookList.tsx
  src/hooks/useGetCategoryId.ts
  src/pages/domestic/[category]/index.tsx
  src/pages/foreign/[category]/index.tsx
  src/store/state.ts
Labels: fix, feat

#234 [#221, #220] 베스트/신간 페이지 api 연결
  src/components/book/previewBookInfo/previewBookInfo.tsx
  src/components/book/previewBookInfo/title.tsx
  src/components/card/bookOverviewCard/bookOverViewCard.tsx
  src/components/card/bookOverviewCard/bookOverViewCardList.tsx
  src/components/layout/bestSellerLayout.tsx
  src/hooks/useFormatDate.ts
  src/hooks/useGetBooks.ts
  src/pages/api/mock/bestSellerMock.ts
  src/pages/domestic/[category]/bestseller/index.tsx
  src/pages/domestic/[category]/newest/index.tsx
  src/pages/domestic/bestseller/index.tsx
  src/pages/domestic/index.tsx
  src/pages/domestic/newest/index.tsx
  src/pages/foreign/[category]/bestseller/index.tsx
  src/pages/foreign/[category]/newest/index.tsx
  src/pages/foreign/bestseller/index.tsx
  src/pages/foreign/newest/index.tsx
  src/pages/test/index.tsx
  src/styles/globals.css
  src/types/api/book.ts
  src/types/bookOverviewType.ts
Labels: feat, refactor

#251 [#242] 결제완료 페이지 UI
  src/components/card/totalPaymentCard/index.tsx
  src/components/card/totalPaymentCard/totalPrice.tsx
  src/components/container/orderCompletedSection/index.tsx
  src/pages/paymented/index.tsx
  src/pages/test/payment/index.tsx
Labels: style, Priority : Low

#256 [#255] 현재 위치한 카테고리 id를 업데이트하는 코드 수정
  src/components/button/sidebar/sidebarRegionButton.tsx
  src/components/button/sidebar/sidebarTab.tsx
  src/components/button/sidebar/sidebarTabController.tsx
  src/components/container/categoryBookList/mainCategoryBookList.tsx
  src/components/container/categoryBookList/subCategoryBookList.tsx
  src/components/container/initialContainer/initialContainer.tsx
  src/hooks/useCheckCategoryUrl.ts
Labels: fix, feat

#228 [#227] 배송정보 입력 컴포넌트 구현
  src/components/button/delivery/searchAddressButton.tsx
  src/components/button/delivery/setDefaultAddressButton.tsx
  src/components/button/delivery/shippingOptionRadio.tsx
  src/components/container/shippingAddressSection/shippingAddressSection.tsx
  src/components/dropDown/deliveryDropDown.tsx
  src/components/dropDown/dropDown.tsx
  src/components/input/delivery/addressInput.tsx
  src/components/input/delivery/addressInputField.tsx
  src/components/input/delivery/addressLabel.tsx
  src/components/input/delivery/addressTextArea.tsx
  src/components/input/delivery/deliveryRequestInput.tsx
  src/components/input/delivery/phoneNumberInput.tsx
  src/components/input/delivery/receiptInput.tsx
  src/components/modal/findAddress/AddressItem.tsx
  src/components/modal/findAddress/findAddressWrapper.tsx
  src/constants/address.tsx
  src/constants/deliveryMenu.ts
  src/constants/dropDownMenu 2.ts
  src/pages/order/index.tsx
  src/pages/test/index.tsx
  src/store/address.ts
  src/styles/globals.css
Labels: feat

#259 [#249] 오늘의 도서 컴포넌트 api 연결
  src/components/book/bookAuthor/bookAuthor.tsx
  src/components/book/bookCategory/bookCategory.tsx
  src/components/card/todayBestBookCard/TodayBestBookCard.tsx
  src/components/container/todayBestSection/todayBestSection.tsx
  src/components/container/todayBestSection/todayBestSlider.tsx
Labels: feat

#257 [#238] 베스트/신간 페이지 장바구니 api 연결
  src/api/basket.ts
  src/components/card/bookOverviewCard/bookOverViewCard.tsx
  src/hooks/useInitialParams.ts
  src/pages/domestic/[category]/bestseller/index.tsx
  src/pages/domestic/[category]/newest/index.tsx
  src/pages/domestic/bestseller/index.tsx
  src/pages/domestic/newest/index.tsx
  src/pages/foreign/[category]/bestseller/index.tsx
  src/pages/foreign/[category]/newest/index.tsx
  src/pages/foreign/bestseller/index.tsx
  src/pages/foreign/newest/index.tsx
  src/types/api/basket.ts
  src/types/api/book.ts
  src/types/bookOverviewType.ts
Labels: feat

#268 [#265] 메인페이지 베스트셀러 섹션 api 연결
  src/components/container/bestsellerSection/bestsellerSection.tsx
Labels: feat

#264 [#241] 결제 페이지 조립
  src/components/card/totalPaymentCard/index.tsx
  src/components/container/shippingAddressSection/shippingAddressSection.tsx
  src/components/dropDown/deliveryDropDown.tsx
  src/components/dropDown/dropDownItem.tsx
  src/pages/order/index.tsx
Labels: feat

#263 [#262] 베스트/신간페이지 카테고리 내 도서가 없을때 UI 적용 + 토큰 환경변수적용
  src/components/card/bookOverviewCard/bookOverViewCard.tsx
  src/components/card/bookOverviewCard/bookOverViewCardList.tsx
  src/components/card/bookOverviewCard/bookOverviewEmptyCard.tsx
  src/pages/domestic/[category]/bestseller/index.tsx
Labels: feat, refactor

#276 [#275] 스켈레톤 UI 적용 로직 수정
  src/components/book/previewBookInfo/previewBookInfo.tsx
  src/components/card/bookOverviewCard/bookOverViewCardList.tsx
  src/components/skeleton/bookOverviewCard/skeleton.tsx
  src/pages/domestic/[category]/bestseller/index.tsx
  src/pages/domestic/[category]/newest/index.tsx
  src/pages/domestic/bestseller/index.tsx
  src/pages/domestic/newest/index.tsx
  src/pages/foreign/[category]/bestseller/index.tsx
  src/pages/foreign/[category]/newest/index.tsx
  src/pages/foreign/bestseller/index.tsx
  src/pages/foreign/newest/index.tsx
  src/pages/test/index.tsx
Labels: refactor

#281 [#280] 모든 레이아웃 컴포넌트에 MainLayout 적용
  src/api/basket.ts
  src/components/book/bookAuthor/bookAuthor.tsx
  src/components/book/previewBookInfo/previewBookInfo.tsx
  src/components/button/actionButton.tsx
  src/components/card/bookOverviewCard/bookOverViewCard.tsx
  src/components/card/bookOverviewCard/bookOverviewMobile.tsx
  src/components/layout/bestSellerLayout.tsx
  src/components/layout/myOrderLayOut.tsx
  src/components/layout/settingPageLayout.tsx
  src/components/profile/editPassword/editPassword.tsx
  src/components/profile/editProfile/editProfile.tsx
  src/hooks/api/useAddToBasket.ts
  src/pages/domestic/[category]/bestseller/index.tsx
  src/pages/domestic/[category]/newest/index.tsx
  src/pages/domestic/bestseller/index.tsx
  src/pages/domestic/newest/index.tsx
  src/pages/foreign/[category]/bestseller/index.tsx
  src/pages/foreign/[category]/newest/index.tsx
  src/pages/foreign/bestseller/index.tsx
  src/pages/foreign/newest/index.tsx
  src/pages/mypage/order/index.tsx
  src/pages/mypage/setting/editPassword/index.tsx
  src/pages/mypage/setting/editProfile/index.tsx
  src/pages/mypage/setting/selectGenre/index.tsx
  src/utils/reactQuery.ts
Labels: refactor

#274 [#208] 토큰관리
  package-lock.json
  package.json
  src/api/member.ts
  src/components/button/header/myPageButton.tsx
  src/components/button/signOutButton.tsx
  src/components/layout/mainLayout.tsx
  src/libs/instance.ts
  src/middleware.ts
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/domestic/[category]/bestseller/index.tsx
  src/pages/domestic/[category]/newest/index.tsx
  src/pages/domestic/bestseller/index.tsx
  src/pages/domestic/newest/index.tsx
  src/pages/foreign/[category]/bestseller/index.tsx
  src/pages/foreign/[category]/newest/index.tsx
  src/pages/foreign/bestseller/index.tsx
  src/pages/foreign/newest/index.tsx
  src/pages/mypage/order/index.tsx
  src/pages/mypage/setting/editPassword/index.tsx
  src/pages/mypage/setting/editProfile/index.tsx
  src/pages/mypage/setting/selectGenre/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/pages/test/carouselTest.tsx
  src/types/ next-auth.d.ts
  src/types/api/member.ts
  tsconfig.json
Labels: feat

#279 [#269] 제품상세페이지 상단 제품 info 디자인 수정 및 스켈레톤 추가
  src/components/card/bookDetailCard/bookDetailCard.tsx
  src/components/card/bookDetailCard/bookDetailImg.tsx
  src/components/card/bookDetailCard/bookDetailInfo.tsx
  src/components/orderNavigator/staticOrderNavigator.tsx
  src/components/skeleton/bookDetailCard/skeleton.tsx
  src/pages/bookdetail/[bookId].tsx
Labels: fix, feat, refactor, style

#286 [#247 ] 카테고리 페이지 버그 수정 및 스켈레톤 추가
  src/components/button/sidebar/sidebarTab.tsx
  src/components/container/categoryBookList/mainCategoryBookList.tsx
  src/components/container/categoryBookList/subCategoryBookList.tsx
  src/hooks/useInitialParams.ts
  src/pages/domestic/[category]/index.tsx
  src/pages/domestic/index.tsx
  src/pages/foreign/[category]/index.tsx
  src/pages/foreign/index.tsx
  src/utils/selectOrder.ts
Labels: fix, feat

#291 [#289] [#290] useUpdate 훅 + 비밀번호 변경 api 연결
  src/api/basket.ts
  src/api/book.ts
  src/api/bookmark.ts
  src/api/community.ts
  src/api/delivery.ts
  src/api/member.ts
  src/api/order.ts
  src/api/payment.ts
  src/api/review.ts
  src/components/button/register/registerButton.tsx
  src/components/carousel/carouselCard.tsx
  src/components/profile/editPassword/editPassword.tsx
  src/components/skeleton/bookOverviewCard/skeleton.tsx
  src/hooks/api/useAddToBasket.ts
  src/hooks/api/useEditPassword.ts
  src/types/api/member.ts
  src/utils/reactQuery.ts
Labels: feat, refactor

#282 [#186] 맞춤 페이지 API연결
  src/api/book.ts
  src/api/cart.ts
  src/api/category.ts
  src/components/book/previewBookInfo/previewBookInfo.tsx
  src/components/book/previewBookInfo/price.tsx
  src/components/button/genre/customPageGenreButton.tsx
  src/components/layout/vacantCustomLayout.tsx
  src/components/skeleton/customSkeleton/genreSkeleton.tsx
  src/components/skeleton/customSkeleton/skeleton.tsx
  src/components/skeleton/previewBookImage/skeleton.tsx
  src/hooks/useGetBasKetQuery.ts
  src/pages/api/mock.ts
  src/pages/bookmarked/index.tsx
  src/pages/custom/index.tsx
  src/pages/test/custom.tsx
  src/pages/test/jotaiTest.tsx
  src/styles/globals.css
  src/types/customPageType.ts
  src/types/previewBookInfoType.ts
  src/utils/compareBooks.ts
  src/utils/createReadMeGenre.ts
  tailwind.config.ts
Labels: feat

#285 [#283] carousel prop이름변경
  src/components/carousel/categoryCarousel.tsx
  src/pages/api/mock/carouselMock.ts
  src/types/carouselType.ts
Labels: fix

#288 [#287] MainLayout 변경 && 찜, 장바구니 페이지 책 이미지 변경 && type변경
  src/components/cart/cartPayment.tsx
  src/pages/bookmarked/index.tsx
  src/pages/cart/index.tsx
  src/pages/custom/index.tsx
  src/store/state.ts
  src/types/cartType.ts
Labels: style

#298 [#240] 베스트/신간 페이지 구매하기 클릭시 전역변수 저장
  src/api/basket.ts
  src/components/card/bookOverviewCard/bookOverViewCard.tsx
  src/components/cart/cartPayment.tsx
  src/hooks/api/useAddToBasket.ts
  src/store/state.ts
  src/types/api/basket.ts
  src/types/api/book.ts
  src/utils/reactQuery.ts
Labels: feat, refactor

#294 [#293] bestseller section 구조및 스타일 수정
  src/components/container/bestsellerSection/bestsellerSection.tsx
  src/pages/domestic/[category]/index.tsx
  src/pages/domestic/index.tsx
  src/pages/foreign/[category]/index.tsx
  src/pages/foreign/index.tsx
  src/pages/index.tsx
  src/pages/test/footer/index.tsx
Labels: feat, style

#301 [#300, #301] 결제페이지 주문상품 + 결제금액 전역변수 연결
  src/components/card/bookPaymentCard/bookPaymentCard.tsx
  src/components/card/bookPaymentCard/bookPaymentCardList.tsx
  src/components/card/bookPaymentCard/bookPaymentCost.tsx
  src/components/card/totalPaymentCard/index.tsx
  src/components/cart/cartPayment.tsx
  src/components/container/orderCompletedSection/index.tsx
  src/components/modal/addCommunityCard/addCommunityCardForm.tsx
  src/hooks/common/useCalculateProductsPrice.ts
  src/hooks/common/useCalculateTotalPrice.ts
  src/pages/api/mock/bookOrderMock.ts
  src/pages/mypage/order/index.tsx
  src/pages/order/index.tsx
  src/pages/test/bookPaymentCard/index.tsx
  src/pages/test/orderPage/index.tsx
Labels: feat

#292 [#270] 책 상세페이지 리뷰 페이지네이션 및 정렬 , 스켈레톤 구현
  public/icons/Noprofile.svg
  src/api/review.ts
  src/components/book/percentage/reviewPercentageOverview.tsx
  src/components/button/bookDetailNav.tsx
  src/components/button/pagination.tsx
  src/components/card/bookDetailCard/bookDetailInfo.tsx
  src/components/card/bookReviewCard/bookReviewCard.tsx
  src/components/card/bookReviewCard/reviewOverviewCard.tsx
  src/components/review/review.tsx
  src/components/skeleton/bookReviewCard/skeleton.tsx
  src/constants/orderList.ts
  src/hooks/usePagination.ts
  src/pages/bookdetail/[bookId].tsx
  src/store/state.ts
  src/types/api/review.ts
Labels: feat

#308 [#307] 장바구니에 페이지에서 아이템 삭제시, 헤더 장바구니 이미지 수량 업데이트 안되는 문제
  src/hooks/useDeleteBasketQuery.ts
Labels: fix

#306 [#305] 배송지 선택 라디오 버튼의 기본 배송지가 다시 클릭되지 않는 문제 해결
  src/components/container/shippingAddressSection/shippingAddressSection.tsx
Labels: fix

#310 [#309] 헤더 장바구니 api 연결
  src/components/layout/mainLayout.tsx
Labels: feat

#299 [#243] 로그인하고 책상세페이지 접속 시 조회수 증가 기능 추가
  src/api/book.ts
  src/pages/bookdetail/[bookId].tsx
  src/types/api/book.ts
Labels: feat

#311 [#244] 제품상세페이지 구매하기, 장바구니 버튼 연결
  src/api/basket.ts
  src/components/card/bookDetailCard/bookDetailCard.tsx
  src/components/orderNavigator/footerOrderNavitgator.tsx
  src/components/orderNavigator/sideOrderNavigator.tsx
  src/components/orderNavigator/staticOrderNavigator.tsx
  src/hooks/useAddItemBasket.ts
  src/hooks/usePayNowItem.ts
  src/pages/bookdetail/[bookId].tsx
  src/types/api/basket.ts
Labels: feat

#328 [#327] DropDown, OrderDate 컴포넌트 주문조회 페이지에 조립
  src/components/container/orderDate/orderDate.tsx
  src/components/layout/myOrderLayOut.tsx
  src/constants/ orderDropDownMenus.ts
  src/pages/mypage/order/index.tsx
Labels: feat

#335 [#338] Mixed content 문제 해결을 위한 메타 태그추가
  src/pages/_document.tsx
Labels: fix

#330 [#295] 제품 상세페이지 찜 버튼 구현
  src/api/bookmark.ts
  src/components/card/bookDetailCard/bookDetailCard.tsx
  src/components/card/bookDetailCard/bookDetailInfo.tsx
  src/components/orderNavigator/footerOrderNavitgator.tsx
  src/components/orderNavigator/sideOrderNavigator.tsx
  src/hooks/useClickLikeButton.ts
  src/pages/bookdetail/[bookId].tsx
  src/types/api/bookmark.ts
  src/utils/reactQuery.ts
Labels: feat

#331 [#296] 제품상세페이지 링크 공유 버튼 구현
  src/components/book/bookInformation/bookInformation.tsx
  src/components/card/bookDetailCard/bookDetailInfo.tsx
  src/components/container/refundTerm/refundTerm.tsx
  src/hooks/common/useCopyLink.ts
Labels: feat

#334 [#333] 페이지 이동 시 로딩스피너 출력
  public/icons/BrandName.svg
  public/icons/LogoFav.svg
  src/components/chip/loadingSpinner.tsx
  src/components/container/initialContainer/initialContainer.tsx
  src/pages/_app.tsx
  src/pages/test/loadingTest.tsx
  tailwind.config.ts
Labels: feat

#332 [#316] 프로필 수정 api 연결
  src/api/member.ts
  src/components/profile/editProfile/editProfile.tsx
  src/constants/sign.ts
  src/hooks/api/useEditProfile.ts
  src/libs/instance.ts
  src/pages/mypage/setting/editProfile/index.tsx
  src/types/api/member.ts
  src/types/editProfileTypes.ts
Labels: feat

#341 [#303] 아임포트 카카오페이 테스트 결제 연동
  src/components/button/payment/paymentButton.tsx
  src/components/card/totalPaymentCard/index.tsx
  src/components/layout/mainLayout.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/order/index.tsx
  src/styles/globals.css
  src/types/index.d.ts
Labels: feat

#349 [#320] 에러페이지 구현
  public/favicon.ico
  public/icons/MainLogoIcon.svg
  src/components/container/error/index.tsx
  src/libs/instance.ts
  src/pages/404.tsx
  src/pages/500.tsx
  src/pages/_document.tsx
Labels: style

#344 [#339] 마이페이지 선호장르 선택 api 연결
  src/api/category.ts
  src/api/member.ts
  src/components/button/genre/genreButton.tsx
  src/components/container/genreSection/genreSection.tsx
  src/constants/queryKey.ts
  src/hooks/api/useSelectGenre.ts
  src/pages/_document.tsx
  src/pages/api/mock.ts
Labels: feat

#348 [#254] 결제상세 페이지 UI
  src/components/card/bookOrderCard/bookOrderCardList.tsx
  src/components/container/orderCompletedSection/index.tsx
  src/components/container/orderDate/orderCount.tsx
  src/pages/mypage/order/[orderId].tsx
Labels: style

#356 [#355] 비로그인 상태의 헤더가 장바구니 아이템을 get 하는 문제해결
  src/components/header/index.tsx
  src/components/layout/mainLayout.tsx
Labels: fix

#345 [#164] 글쓰기 모달 api 연결
  src/api/community.ts
  src/api/review.ts
  src/components/button/header/writePostButton.tsx
  src/components/button/kebab/kebabButton.tsx
  src/components/button/kebab/kebabDropDownButton.tsx
  src/components/card/bookReviewCard/myReviewCard.tsx
  src/components/card/communityCard/communityCard.tsx
  src/components/card/communityCard/communityCardList.tsx
  src/components/header/navigationTab.tsx
  src/components/layout/communityLayout.tsx
  src/components/modal/addCommunityCard/addCommunityCardForm.tsx
  src/components/modal/addCommunityCard/index.tsx
  src/components/modal/addCommunityCard/previewBookInfoPagination.tsx
  src/components/modal/addReview/addReviewForm.tsx
  src/components/modal/addReview/index.tsx
  src/components/modal/getRefund/getRefundForm.tsx
  src/hooks/useFormControl.ts
  src/pages/test/index.tsx
  src/types/api/community.ts
  src/types/communityCardType.ts
Labels: feat

#343 [#342] 회원가입페이지 오류메시지 &&찜페이지 버그 fix && 맞춤페이지 버그 FIX
  src/components/layout/vacantCustomLayout.tsx
  src/components/skeleton/customSkeleton/skeleton.tsx
  src/hooks/useBookMarkInfiniteQuery.ts
  src/hooks/useSignUpMutation.ts
  src/pages/bookmarked/index.tsx
  src/pages/custom/index.tsx
  src/pages/signup/index.tsx
  src/types/api/member.ts
  src/types/signType.ts
Labels: fix

#354 [#336] 마이페이지 나의 리뷰 페이지 api 연결
  src/api/member.ts
  src/components/card/bookReviewCard/myReviewCard.tsx
  src/components/card/bookReviewCard/myReviewCardList.tsx
  src/pages/api/mock/myReviewMock.ts
  src/pages/mypage/review/index.tsx
  src/types/api/review.ts
  src/types/bookReviewType.ts
Labels: feat, style

#357 [#350] 결제페이지 필수동의사항 체크되어야 진행되도록 수정
  src/components/button/payment/paymentButton.tsx
  src/components/card/totalPaymentCard/index.tsx
  src/components/container/terms/terms.tsx
  src/components/dropDown/deliveryDropDown.tsx
  src/pages/order/index.tsx
Labels: refactor

#365 [#364] 메인페이지 맞춤도서 섹션 api 연결
  src/components/button/genre/customSectionGenreButton.tsx
  src/components/container/customSection/customSection.tsx
  src/components/container/customSection/genreSelection.tsx
  src/components/container/customSection/nonSelectedCustomSection.tsx
  src/components/layout/vacantCustomLayout.tsx
  src/pages/index.tsx
  src/pages/test/footer/index.tsx
Labels: feat

#367 [#366] 회원가입페이지 , 가입후 로그인을 next_Auth로 변경 && payment type수정 && 주문페이지 dropDown "전체조회"삭제
  src/components/card/bookOverviewCard/bookOverViewCard.tsx
  src/components/cart/cartPayment.tsx
  src/components/container/orderDate/orderDate.tsx
  src/constants/ORDER_DROPDOWN_MENUS.ts
  src/hooks/usePayNowItem.ts
  src/hooks/useSignUpMutation.ts
  src/pages/api/mock/bookOrderMock.ts
  src/pages/mypage/order/index.tsx
  src/types/cartType.ts
Labels: fix

#371 [#370] enabled 설정 수정
  src/utils/reactQuery.ts
Labels: bug, fix

#368 [#206] 리뷰모달 api 연결
  src/api/community.ts
  src/api/member.ts
  src/api/review.ts
  src/components/book/bookAuthor/bookAuthor.tsx
  src/components/button/addcommunityButton.tsx
  src/components/button/register/registerButton.tsx
  src/components/card/bookOrderCard/bookOrderCard.tsx
  src/components/card/bookOrderCard/bookOrderCardList.tsx
  src/components/card/bookReviewCard/myReviewCard.tsx
  src/components/card/communityCard/communityCard.tsx
  src/components/header/index.tsx
  src/components/header/mypageTab.tsx
  src/components/header/settingTab.tsx
  src/components/layout/communityLayout.tsx
  src/components/layout/mainLayout.tsx
  src/components/layout/myOrderLayOut.tsx
  src/components/layout/settingPageLayout.tsx
  src/components/modal/addCommunityCard/index.tsx
  src/components/modal/addReview/addReviewForm.tsx
  src/components/modal/addReview/index.tsx
  src/components/modal/addReview/titleContentTable.tsx
  src/components/modal/alertModal/index.tsx
  src/components/modal/cart/cartPaymentModal.tsx
  src/components/modal/findAddress/AddressItem.tsx
  src/components/review/review.tsx
  src/components/skeleton/bookOverviewCard/skeleton.tsx
  src/hooks/useFormControl.ts
  src/pages/test/modaltest.tsx
  src/types/api/community.ts
Labels: feat

#372 [#358] 소셜 로그인 auth 확인 기능
  .gitignore
  package.json
  public/icons/GoogleIcon.svg
  public/icons/KakaoIcon.png
  public/icons/KakaoIcon.svg
  public/icons/NaverIcon.svg
  src/api/social.ts
  src/components/chip/socialCircle.tsx
  src/components/layout/mainLayout.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
Labels: bug, feat, Priority : High

#369 [#360] 광고/이벤트 섹션 구현
  public/images/AdImage.png
  public/images/EventImage1.png
  public/images/EventImage2.png
  public/images/EventImage3.png
  public/images/EventImageMobile1.png
  public/images/EventImageMobile2.png
  public/images/EventImageMobile3.png
  src/components/card/advertisementCard/advertisementCard.tsx
  src/components/carousel/eventCarousel.tsx
  src/components/container/eventSection/eventSection.tsx
  src/constants/eventImages.ts
  src/constants/size/previewBookImageSize.ts
  src/constants/style/eventSectionSize.ts
  src/pages/domestic/[category]/index.tsx
  src/pages/domestic/index.tsx
  src/pages/foreign/[category]/index.tsx
  src/pages/foreign/index.tsx
  src/pages/index.tsx
Labels: feat

#376 [#25] header searchInput 검색 api 연결
  src/components/container/search/searchBookList.tsx
  src/components/header/index.tsx
  src/components/input/headerSearchInput.tsx
  src/components/input/searchInput.tsx
  src/components/layout/sidebarLayout.tsx
  src/pages/search/index.tsx
  src/types/api/book.ts
Labels: feat

#385 [#386] 화면 스크롤해도 로딩스피너가 고정되게 보이도록 수정
  src/components/chip/loadingSpinner.tsx
Labels: fix

#381 [#382] 푸터 스타일 조정 후 메인페이지에 추가
  src/components/footer/footer.tsx
  src/pages/index.tsx
Labels: refactor, style

#380 [#379] 회원가입/결제 페이지에 이용약관 모달띄우기
  public/images/EventImage2.png
  public/images/EventImage3.png
  public/images/EventImage4.png
  public/images/EventImageDefault.png
  public/images/EventImageMobile2.png
  public/images/EventImageMobile3.png
  public/images/EventImageMobile4.png
  public/images/EventImageMobileDefault.png
  src/components/button/payment/paymentButton.tsx
  src/components/card/totalPaymentCard/index.tsx
  src/components/carousel/eventCarousel.tsx
  src/components/container/terms/terms.tsx
  src/components/modal/termsDetailModal/termsDetailModal.tsx
  src/constants/eventImages.ts
  src/constants/sign.ts
  src/constants/termsContent.ts
  src/pages/order/index.tsx
  src/pages/signup/index.tsx
Labels: feat, refactor

#389 [#383] 실시간 인기도서 이미지 넘침문제 해결
  src/components/book/previewBookInfo/previewBookInfo.tsx
  src/components/card/todayBestBookCard/TodayBestBookCard.tsx
Labels: refactor, style

#387 [#388] 제품상세페이지 리팩토링
  src/api/bookmark.ts
  src/components/card/bookDetailCard/bookDetailCard.tsx
  src/components/card/bookDetailCard/bookDetailInfo.tsx
  src/components/container/todayBestSection/todayBestSection.tsx
  src/components/orderNavigator/footerOrderNavitgator.tsx
  src/components/orderNavigator/sideOrderNavigator.tsx
  src/hooks/useAddItemBasket.ts
  src/hooks/useClickBookmarkButton.ts
  src/hooks/useClickLikeButton.ts
  src/hooks/usePayNowItem.ts
  src/pages/bookdetail/[bookId].tsx
  src/pages/bookdetail/index.tsx
Labels: fix, refactor

#393 [#392] 스타일 수정
  public/images/AdImage.png
  public/images/AdImageCategory.png
  src/components/book/previewBookInfo/previewBookInfo.tsx
  src/components/card/bookOverviewCard/bookOverViewCard.tsx
  src/components/card/bookOverviewCard/bookOverViewCardList.tsx
  src/components/container/eventSection/eventSection.tsx
  src/constants/eventImages.ts
  src/pages/domestic/[category]/bestseller/index.tsx
  src/pages/domestic/[category]/index.tsx
  src/pages/domestic/bestseller/index.tsx
  src/pages/domestic/index.tsx
  src/pages/foreign/[category]/bestseller/index.tsx
  src/pages/foreign/[category]/index.tsx
  src/pages/foreign/bestseller/index.tsx
  src/pages/foreign/index.tsx
  src/pages/index.tsx
  src/pages/search/index.tsx
Labels: style, Priority : Low

#394 [#384] 카테고리 페이지 베스트셀러 디자인 일부 수정
  src/components/container/bestsellerSection/bestsellerSection.tsx
  src/pages/domestic/[category]/index.tsx
  src/pages/foreign/[category]/index.tsx
Labels: fix, style

#395 [#396] 이미지 리팩토링
  next.config.mjs
  public/icons/AddCommunityButton.svg
  public/icons/BookCharacterGray.svg
  public/icons/BookLabelBottomGrayIcon.svg
  public/icons/BookLabelBottomIcon.svg
  public/icons/BookLabelGrayIcon.svg
  public/icons/BrandName.svg
  public/icons/Calendar.svg
  public/icons/CameraImageIcon.svg
  public/icons/CartIcon.svg
  public/icons/CheckBox.svg
  public/icons/CheckIcon.svg
  public/icons/CheckedCheckBox.svg
  public/icons/Close.svg
  public/icons/DeleteIcon.svg
  public/icons/EditIcon.svg
  public/icons/EraserSearchValue.svg
  public/icons/EyeClose.svg
  public/icons/EyeOpen.svg
  public/icons/FilledStar.svg
  public/icons/HeartEmptyIcon.svg
  public/icons/HeartFillIcon.svg
  public/icons/Info.svg
  public/icons/Kebab.svg
  public/icons/Line.svg
  public/icons/MainLogoIcon.svg
  public/icons/NextIcon.svg
  public/icons/Noprofile.svg
  public/icons/PrevIcon.svg
  public/icons/PrimaryArrowRight.svg
  public/icons/ProfileIcon.svg
  public/icons/RightArrow.svg
  public/icons/ScrollToTopButton.svg
  public/icons/SearchIcon.svg
  public/icons/ShareIcon.svg
  public/icons/UpArrow.svg
Labels: feat, refactor

#373 [#346] 환불모달 api
  src/api/community.ts
  src/api/delivery.ts
  src/api/review.ts
  src/components/card/bookOrderCard/bookOrderCard.tsx
  src/components/card/bookOrderCard/bookOrderCardList.tsx
  src/components/modal/addCommunityCard/addCommunityCardForm.tsx
  src/components/modal/addReview/addReviewForm.tsx
  src/components/modal/getRefund/getRefundForm.tsx
  src/components/modal/getRefund/index.tsx
  src/hooks/useFormControl.ts
  src/pages/mypage/order/index.tsx
  src/pages/test/modaltest.tsx
  src/types/api/community.ts
  src/types/bookOrderType.ts
Labels: feat

#399 [#398] 모달창/아이콘 사이즈 조절
  package-lock.json
  package.json
  public/icons/HeartFillIcon.svg
  src/components/modal/addCommunityCard/addCommunityCardForm.tsx
  src/components/modal/addReview/addReviewForm.tsx
  src/components/modal/findAddress/findAddressForm.tsx
  src/components/modal/modalContainer.tsx
  src/components/modal/modalLayout.tsx
  src/components/modal/termsDetailModal/termsDetailModal.tsx
  tailwind.config.ts
Labels: refactor, style

#403 [테스트] 소셜 로그인 구현
  src/components/chip/socialCircle.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/signin/[socialType].tsx
Labels: feat

#402 [#401] 도서 컴포넌트 저자명 표시 방식 변경
  src/components/book/bookAuthor/bookAuthor.tsx
  src/components/book/previewBookInfo/authors.tsx
  src/components/card/bookDetailCard/bookDetailCard.tsx
  src/components/card/bookDetailCard/bookDetailInfo.tsx
  src/components/card/bookOverviewCard/bookOverViewCard.tsx
  src/hooks/common/useEditAuthorsName.ts
  src/pages/bookdetail/[bookId].tsx
Labels: fix, style

#404 [#358] 소셜 로그인 기능 구현
  src/components/chip/socialCircle.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/signin/[socialType].tsx
Labels: feat

#397 [#353] 커뮤니티 이모티콘 api 연결
  public/images/ExcitedEmoji.png
  src/api/community.ts
  src/components/book/bookAuthor/bookAuthor.tsx
  src/components/card/bookDetailCard/bookDetailCard.tsx
  src/components/card/communityCard/communityCard.tsx
  src/components/card/communityCard/communityCardList.tsx
  src/components/card/communityCard/emoji/emojiButton.tsx
  src/components/card/communityCard/emoji/emojiButtonContainer.tsx
  src/components/layout/communityLayout.tsx
  src/components/modal/alertModal/index.tsx
  src/components/modal/profile/index.tsx
  src/components/modal/profile/profileModalForm.tsx
  src/constants/address.ts
  src/constants/communityEmoji.ts
  src/constants/queryKey.ts
  src/hooks/useFormControl.ts
  src/hooks/useUpdateEmoji.ts
  src/pages/community/index.tsx
  src/types/api/community.ts
  src/types/api/member.ts
  src/types/communityCardType.ts
  src/utils/reactQuery.ts
Labels: feat, style

#421 [#420] 디자인 수정 요청 반영
  public/icons/ReadmeLogo.svg
  public/images/AdImage.png
  src/components/book/previewBookInfo/previewBookInfo.tsx
  src/components/card/communityCard/communityCard.tsx
  src/components/carousel/carousel.tsx
  src/components/container/customSection/customSection.tsx
  src/components/container/customSection/nonLoggedInCustomSection.tsx
  src/components/container/customSection/nonSelectedCustomSection.tsx
  src/components/container/customSection/recommendationContent.tsx
  src/components/container/todayBestSection/todayBestSection.tsx
  src/components/footer/footer.tsx
  src/components/header/index.tsx
  src/components/header/navigationTab.tsx
  src/components/input/headerSearchInput.tsx
  src/components/input/searchInput.tsx
  src/components/layout/headerLayout.tsx
  src/styles/globals.css
Labels: refactor, style

#428 [#419] 주문상세 api
  src/api/delivery.ts
  src/components/book/percentage/reviewPercentageOverview.tsx
  src/components/book/previewBookInfo/previewBookInfo.tsx
  src/components/button/header/categoryTabButton.tsx
  src/components/card/bookDetailCard/bookDetailCard.tsx
  src/components/card/bookOrderCard/bookOrderCard.tsx
  src/components/card/bookOrderCard/bookOrderCardList.tsx
  src/components/card/bookOverviewCard/bookOverViewCard.tsx
  src/components/card/bookOverviewCard/bookOverViewCardList.tsx
  src/components/card/bookPaymentCard/bookPaymentCard.tsx
  src/components/card/bookPaymentCard/bookPaymentCardList.tsx
  src/components/card/bookReviewCard/myReviewCardList.tsx
  src/components/card/communityCard/communityCardList.tsx
  src/components/card/totalPaymentCard/index.tsx
  src/components/container/customSection/customSection.tsx
  src/components/container/customSection/genreSelection.tsx
  src/components/container/customSection/nonLoggedInCustomSection.tsx
  src/components/container/orderCompletedSection/index.tsx
  src/components/container/orderDate/orderCount.tsx
  src/components/input/delivery/addressInput.tsx
  src/components/layout/bestSellerLayout.tsx
  src/components/layout/myOrderLayOut.tsx
  src/components/layout/settingPageLayout.tsx
  src/components/layout/sidebarLayout.tsx
  src/components/modal/addCommunityCard/addCommunityCardForm.tsx
  src/components/modal/addCommunityCard/previewBookInfoPagination.tsx
  src/components/modal/findAddress/index.tsx
  src/components/modal/profile/index.tsx
  src/constants/termsContent.ts
  src/hooks/common/useCalculateProductsPrice.ts
  src/hooks/common/useCalculateTotalPrice.ts
  src/hooks/useAddItemBasket.ts
  src/hooks/useClickBookmarkButton.ts
  src/hooks/usePayNowItem.ts
  src/pages/api/mock/bookOrderMock.ts
  src/pages/bookdetail/[bookId].tsx
  src/pages/cart/index.tsx
  src/pages/mypage/order/[orderId].tsx
  src/pages/mypage/order/index.tsx
  src/pages/paymented/index.tsx
  src/pages/test/bookPaymentCard/index.tsx
  src/pages/test/payment/index.tsx
  src/types/api/book.ts
  src/types/api/delivery.ts
  src/types/api/next-auth.d.ts
  src/types/api/onClickType.ts
  src/types/bookOverviewType.ts
  src/types/bookReviewType.ts
  src/types/cartType.ts
Labels: feat

#424 [#423] 모달 내부 검색창 엔터키로도 검색 가능하도록 수정
  src/components/input/modalSearchInput.tsx
  src/components/modal/findAddress/findAddressForm.tsx
  src/hooks/useSearchDebounce.ts
Labels: refactor, style

#433 [#431] 나의 커뮤니티 글 없을때 UI 추가
  src/components/card/communityCard/communityCardList.tsx
Labels: refactor

#435 [#427] 소셜 로그인인 경우 비밀번호 변경 탭이 안보이게 수정
  src/components/button/header/myPageButton.tsx
  src/components/button/signOutButton.tsx
  src/components/header/settingTab.tsx
  src/pages/signin/[socialType].tsx
  src/store/state.ts
Labels: fix, feat

#437 [#436] 베스트셀러 섹션 스크롤 삭제
  src/components/container/bestsellerSection/bestsellerSection.tsx
Labels: fix, style

#451 [#448] 글쓰기 모달 책 정렬 수정
  src/components/modal/addCommunityCard/previewBookInfoPagination.tsx
Labels: fix, style

#450 [#429,#449] 결제 페이지 & 결제 완료 페이지 배송 api 연결
  src/api/cart.ts
  src/api/delivery.ts
  src/api/member.ts
  src/components/book/bookAuthor/bookAuthor.tsx
  src/components/button/delivery/setDefaultAddressButton.tsx
  src/components/button/payment/paymentButton.tsx
  src/components/card/bookDetailCard/bookDetailCard.tsx
  src/components/card/bookOverviewCard/bookOverViewCard.tsx
  src/components/card/bookPaymentCard/bookPaymentCardList.tsx
  src/components/card/totalPaymentCard/index.tsx
  src/components/cart/cartPayment.tsx
  src/components/container/shippingAddressSection/shippingAddressSection.tsx
  src/components/dropDown/deliveryDropDown.tsx
  src/components/input/delivery/addressInput.tsx
  src/components/input/delivery/deliveryRequestInput.tsx
  src/components/input/delivery/phoneNumberInput.tsx
  src/components/input/delivery/receiptInput.tsx
  src/hooks/common/useAddressSplitter.ts
  src/hooks/common/useCalculateTotalPrice.ts
  src/hooks/common/useGetOrderTitle.ts
  src/hooks/usePayNowItem.ts
  src/pages/mypage/order/[orderId].tsx
  src/pages/paymented/index.tsx
  src/store/deliveryInfo.ts
  src/store/orderInfo.ts
  src/types/api/cart.ts
  src/types/deliveryInfo.ts
Labels: feat

#446 [#443] 책 상세페이지 디자인 일부 수정
  src/components/book/percentage/reviewPercentageOverview.tsx
  src/components/card/bookDetailCard/bookDetailInfo.tsx
  src/components/container/initialContainer/initialContainer.tsx
  src/components/review/review.tsx
  src/pages/bookdetail/[bookId].tsx
Labels: fix, refactor

#447 [#438] 커뮤니티 페이지 레이아웃 수정
  src/components/card/communityCard/communityCardList.tsx
  src/components/layout/communityLayout.tsx
  src/hooks/useCustomInfiniteQuery.ts
Labels: fix

#452 [#304] KG 이니시스로 테스트 결제 PG 변경
  src/components/button/payment/paymentButton.tsx
Labels: feat

#454 [#453] 카테고리, 베스트 신간에 리액트 쿼리 캐시 활용
  src/api/book.ts
  src/hooks/useCustomInfiniteQuery.ts
  src/pages/domestic/[category]/bestseller/index.tsx
  src/pages/domestic/[category]/index.tsx
  src/pages/domestic/[category]/newest/index.tsx
  src/pages/domestic/bestseller/index.tsx
  src/pages/domestic/index.tsx
  src/pages/domestic/newest/index.tsx
  src/pages/foreign/[category]/bestseller/index.tsx
  src/pages/foreign/[category]/index.tsx
  src/pages/foreign/[category]/newest/index.tsx
  src/pages/foreign/bestseller/index.tsx
  src/pages/foreign/index.tsx
  src/pages/foreign/newest/index.tsx
  src/utils/reactQuery.ts
Labels: refactor

#456 [#455] header border 수정
  src/components/header/categoryTab.tsx
  src/components/header/mypageTab.tsx
  src/components/header/navigationTab.tsx
  src/components/layout/headerLayout.tsx
Labels: style

#458 [#457] 맞춤도서 섹션 여백 변경
  src/components/container/customSection/customSection.tsx
  src/components/container/customSection/genreSelection.tsx
Labels: style

#460 [#459] 디자인 2차 수정 일부 적용
  public/icons/DefaultLogo.svg
  src/components/button/header/bookmarkButton.tsx
  src/components/button/header/cartButton.tsx
  src/components/button/header/readmeButton.tsx
  src/components/header/index.tsx
  src/components/input/headerSearchInput.tsx
  src/components/input/modalSearchInput.tsx
  src/components/layout/sidebarLayout.tsx
Labels: style

#464 refactor: 메인페이지 신간도서 18개 받아오도록 수정
  src/components/header/categoryTab.tsx
  src/components/header/mypageTab.tsx
  src/components/header/navigationTab.tsx
  src/components/header/settingTab.tsx
  src/pages/index.tsx
Labels: refactor

#466 style: 헤더수정
  src/components/header/mypageTab.tsx
  src/components/header/settingTab.tsx
Labels: style
